fastest_lap_point = 0
pole_point = 0

[gp_point_allocation]
1 = 25
2 = 18
3 = 15
4 = 12
5 = 10
6 = 8
7 = 6
8 = 4
9 = 2
10 = 1

[sprint_point_allocation]
1 = 8
2 = 7
3 = 6
4 = 5
5 = 4
6 = 3
7 = 2
8 = 1